"""Generate synchronized developer documentation catalogs."""

from __future__ import annotations

import sys
from pathlib import Path
from typing import Optional

PROJECT_ROOT = Path(__file__).resolve().parents[1]
PYTHON_ROOT = PROJECT_ROOT / "python"
if str(PYTHON_ROOT) not in sys.path:
    sys.path.insert(0, str(PYTHON_ROOT))


def generate_docs(output_dir: Path = PROJECT_ROOT / "docs" / "generated") -> tuple[Path, ...]:
    """Generate developer catalogs from implementation metadata."""

    from metrology_process_planner.devtools import build_developer_catalog

    catalog = build_developer_catalog()
    output_dir.mkdir(parents=True, exist_ok=True)
    files = (
        _write_table(output_dir / "mode-catalog.md", "Mode Catalog", catalog.modes),
        _write_table(output_dir / "command-catalog.md", "Command Catalog", catalog.commands),
        _write_table(
            output_dir / "render-profile-catalog.md",
            "Render Profile Catalog",
            catalog.render_profiles,
        ),
        _write_text(
            output_dir / "workflow-catalog.md",
            "Workflow Catalog\n\nGenerated from mode metadata.\n",
        ),
        _write_text(
            output_dir / "session-schema-summary.md",
            "Session Schema Summary\n\nGenerated by project health tooling.\n",
        ),
        _write_text(
            output_dir / "recipe-schema-summary.md",
            "Recipe Schema Summary\n\nGenerated by project health tooling.\n",
        ),
        _write_text(
            output_dir / "artifact-schema-summary.md",
            "Artifact Schema Summary\n\nGenerated by project health tooling.\n",
        ),
        _write_text(
            output_dir / "state-machine-diagrams.md",
            "State Machine Diagrams\n\nSee docs/UI_STATE_MACHINES.md.\n",
        ),
    )
    return files


def main(argv: Optional[list[str]] = None) -> int:
    """Run documentation generation from the command line."""

    output_dir = Path(argv[0]) if argv else PROJECT_ROOT / "docs" / "generated"
    for path in generate_docs(output_dir):
        print(path)
    return 0


def _write_table(path: Path, title: str, rows: tuple[dict[str, object], ...]) -> Path:
    if not rows:
        return _write_text(path, f"{title}\n\nNo rows.\n")
    keys = tuple(rows[0].keys())
    lines = [
        title,
        "",
        "| " + " | ".join(keys) + " |",
        "| " + " | ".join("---" for _ in keys) + " |",
    ]
    for row in rows:
        lines.append("| " + " | ".join(str(row.get(key, "")) for key in keys) + " |")
    return _write_text(path, "\n".join(lines) + "\n")


def _write_text(path: Path, text: str) -> Path:
    path.write_text(text, encoding="utf-8")
    return path


if __name__ == "__main__":
    raise SystemExit(main(sys.argv[1:]))
